name: eddies_env
channels:
  - conda-forge
dependencies:
  - jupyterlab
  - argopy
  - cartopy
  - pandas
  - xarray
  - numpy
  - matplotlib
  - ipywidgets
  - seaborn
  - ipython
  - voila
  - widgetsnbextension