name: eddies_env
channels:
  - conda-forge
dependencies:
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.12.13
  - aiosignal=1.3.2
  - anyio=4.9.0
  - appnope=0.1.4
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=21.2.0
  - argopy=1.2.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.5
  - attrs=25.3.0
  - babel=2.17.0
  - beautifulsoup4=4.13.4
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - blosc=1.21.6
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.6.15
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cartopy=0.24.0
  - certifi=2025.6.15
  - cffi=1.17.1
  - cftime=1.6.4
  - charset-normalizer=3.4.2
  - comm=0.2.2
  - contourpy=1.3.2
  - cycler=0.12.1
  - debugpy=1.8.14
  - decorator=5.2.1
  - defusedxml=0.7.1
  - erddapy=2.2.4
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - fonttools=4.58.4
  - fqdn=1.5.1
  - freetype=2.13.3
  - frozenlist=1.6.0
  - fsspec=2025.2.0
  - geos=3.13.1
  - h11=0.16.0
  - h2=4.2.0
  - h5netcdf=1.6.1
  - h5py=3.14.0
  - hdf4=4.2.15
  - hdf5=1.14.6
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - idna=3.10
  - importlib-metadata=8.7.0
  - importlib_resources=6.5.2
  - ipykernel=6.29.5
  - ipython=9.3.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.7
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - json5=0.12.0
  - jsonpointer=3.0.0
  - jsonschema=4.24.0
  - jsonschema-specifications=2025.4.1
  - jsonschema-with-format-nongpl=4.24.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.16.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.3
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.15
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libaec=1.1.4
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcurl=8.14.1
  - libcxx=20.1.7
  - libdeflate=1.24
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.0
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgfortran=5.0.0
  - libgfortran5=14.2.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libnetcdf=4.9.2
  - libnghttp2=1.64.0
  - libopenblas=0.3.30
  - libpng=1.6.49
  - libsodium=1.0.20
  - libsqlite=3.50.1
  - libssh2=1.11.1
  - libtiff=4.7.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxml2=2.13.8
  - libzip=1.11.2
  - libzlib=1.3.1
  - llvm-openmp=20.1.7
  - lz4-c=1.10.0
  - markupsafe=3.0.2
  - matplotlib=3.10.3
  - matplotlib-base=3.10.3
  - matplotlib-inline=0.1.7
  - mistune=3.1.3
  - multidict=6.5.0
  - munkres=1.1.4
  - nbclient=0.10.2
  - nbconvert=7.16.6
  - nbconvert-core=7.16.6
  - nbconvert-pandoc=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - netcdf4=1.7.2
  - notebook-shim=0.2.4
  - numpy=1.26.4
  - openjpeg=2.5.3
  - openssl=3.5.0
  - overrides=7.7.0
  - packaging=25.0
  - pandas=2.3.0
  - pandoc=3.7.0.2
  - pandocfilters=1.5.0
  - parso=0.8.4
  - patsy=1.0.1
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.2.1
  - pip=25.1.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.8
  - proj=9.6.2
  - prometheus_client=0.22.1
  - prompt-toolkit=3.0.51
  - propcache=0.3.1
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.2
  - pyobjc-core=11.1
  - pyobjc-framework-cocoa=11.1
  - pyparsing=3.2.3
  - pyproj=3.7.1
  - pyshp=2.3.1
  - pysocks=1.7.1
  - python=3.12.11
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.1
  - python-json-logger=2.0.7
  - python-tzdata=2025.2
  - python_abi=3.12
  - pytz=2025.2
  - pyyaml=6.0.2
  - pyzmq=27.0.0
  - qhull=2020.2
  - readline=8.2
  - referencing=0.36.2
  - requests=2.32.4
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.25.1
  - scipy=1.15.2
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.3
  - setuptools=80.9.0
  - shapely=2.1.1
  - six=1.17.0
  - snappy=1.2.1
  - sniffio=1.3.1
  - soupsieve=2.7
  - sqlite=3.50.1
  - stack_data=0.6.3
  - statsmodels=0.14.4
  - terminado=0.18.1
  - tinycss2=1.4.0
  - tk=8.6.13
  - tomli=2.2.1
  - toolz=1.0.0
  - tornado=6.5.1
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20250516
  - typing-extensions=4.14.0
  - typing_extensions=4.14.0
  - typing_utils=0.1.0
  - tzdata=2025b
  - unicodedata2=16.0.0
  - uri-template=1.3.0
  - urllib3=2.5.0
  - voila=0.5.8
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - websockets=15.0.1
  - wheel=0.45.1
  - widgetsnbextension=4.0.14
  - xarray=2024.2.0
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - yaml=0.2.5
  - yarl=1.20.1
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.7
